Add support for receiving youtubeApiKey and rendering Youtube Videos
vtex-apps/butik pull request #1
Opened 2019-02-20 13:05 UTC by Lurian

#### What is the purpose of this pull request?

Add apiKey prop to `Youtube` and `Video` components. This is necessary for video URLs (e.g. Youtube) which needs an API key.

The Catalog Service now also returns an array of videos URLs of the product. This information is now being properly received and passed to the Carousel component for video rendering in the Product Page.

#### What problem is this solving?

#### How should this be manually tested?

#### Screenshots or example usage
![image](https://user-images.githubusercontent.com/3064099/53035455-386bd900-3454-11e9-8bc5-0805c505b269.png)

![image](https://user-images.githubusercontent.com/3064099/53093637-b97bac80-34f6-11e9-8d2a-89ee878a0ba8.png)

#### Types of changes
- [ ] Refactor (non-breaking change which improves security, performance or maintainability)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2019-02-20 13:58 UTC, klzns requested changes

2019-02-20 13:58 UTC, klzns commented on react/components/Video/Youtube.js
> +  apiKey: PropTypes.string,
Add `.isRequired` here and in other required props.

2019-02-20 14:03 UTC, GustavoMA requested changes

2019-02-20 14:03 UTC, GustavoMA commented on react/components/Video/index.js
> +  apiKey: PropTypes.string,
Describe prop type with a brief comment :smile:

2019-02-20 14:03 UTC, GustavoMA commented on react/components/Video/index.js
>    }
shouldn't this component `return null` if the url isn't a youtube or vimeo?

2019-02-21 19:07 UTC, klzns approved these changes

2019-02-22 17:20 UTC, GustavoMA approved these changes

2019-02-22 17:47 UTC, merged