Fix/carousel image error
vtex-apps/butik pull request #7
Opened 2019-09-05 17:29 UTC by tkovs

#### What is the purpose of this pull request?
Fix the infinite Loader when a Carousel slide has problems

#### How should this be manually tested?
By adding wrong urls to `Carousel/index.mdx` and check the Carousel page on docz locally.

#### Screenshots or example usage

#### Types of changes
- [x] Refactor (non-breaking change which improves security, performance or maintainability)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2019-09-05 17:49 UTC, tkovs commented on react/components/Carousel/index.js
> +  failedImageIndexes: [],
Basicamente eu anoto a posição dos slides que deram problema, e na hora de exibir os slides eu mostro o placeholder caso o index do slide tenha sido anotado anteriormente

2019-09-05 17:50 UTC, tkovs commented on react/components/Carousel/index.js
> +      const thumbPromises = slides.map((slide, i) => {
Antes era usado um flatMap simulado um map com filter, pois ignorava videos que davam problema. Agora até mesmo um video com problema mostra placeholder.

2019-09-05 17:50 UTC, tkovs commented on react/components/Video/Vimeo.js
> +        .catch(() => reject())
Não estava conseguindo capturar esse catch na promise thumbUrl lá no componente Carousel.

2019-09-05 18:03 UTC, Lurian approved these changes

2019-09-09 19:37 UTC, Lurian requested changes

2019-09-09 19:37 UTC, Lurian commented on CHANGELOG.md
> +- Carousel slide error runs into an infinite Loader
```suggestion
- Carousel slide error running into an infinite loading state
```

2019-09-09 19:37 UTC, Lurian commented on react/components/Carousel/index.js
> +    const slides = this.props.slides.map(slide => ({ ...slide }))
```suggestion
    const slides = this.props.slides ? [...this.props.slides] : []
```

2019-09-09 20:12 UTC, Lurian approved these changes

2019-09-09 20:34 UTC, merged